export const LOAD_MEALS_TO_ADD = 'LOAD_MEALS_TO_ADD';
export const LOAD_MEALS_TO_REMOVE = 'LOAD_MEALS_TO_REMOVE';
export const ADD_TO_MACHINE = 'ADD_TO_MACHINE';
export const ADD_TO_MACHINE_SUCCESS = 'ADD_TO_MACHINE_SUCCESS';
export const REMOVE_FROM_MACHINE = 'REMOVE_FROM_MACHINE';
export const REMOVE_FROM_MACHINE_SUCCESS = 'REMOVE_FROM_MACHINE_SUCCESS';